# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ProgramacaoAplicadaGrupo4
                                 A QGIS plugin
 Solução do Grupo 4
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-05-04
        copyright            : (C) 2023 by Grupo 4
        emails               : e.tadeu.eb@ime.eb.br
                               raulmagno@ime.eb.br
                               arthur.cavalcante@ime.eb.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Grupo 4'
__date__ = '2023-05-04'
__copyright__ = '(C) 2023 by Grupo 4'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'


from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.Qt import QVariant
from qgis.core import (QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingMultiStepFeedback,
                       QgsProcessingParameterVectorLayer,
                       QgsProcessingParameterRasterLayer,
                       QgsExpression,
                       QgsFields,
                       QgsFeature,
                       QgsField,
                       QgsGeometry,
                       QgsPointXY)
import processing


class Projeto2Solucao(QgsProcessingAlgorithm):
    """
    
    Este algoritmo realiza verificações topologicas em conjuntos de dados de recursos hidricos.

    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    DRENAGENS = 'DRENAGENS'
    VERTSUMI = 'VERTSUMI'
    MASSASDAGUA = 'MASSASDAGUA'
    #OCEAN_LAYER = 'OCEAN_LAYER'
    #DITCH_LAYER = 'DITCH_LAYER'
    FLAGPOINT = 'FLAGPOINT'
    FLAGLINE = 'FLAGLINE'
    FLAGPOLYGON = 'FLAGPOLYGON'

    def initAlgorithm(self, config):

        # Camadas de Entrada.
        self.addParameter(QgsProcessingParameterVectorLayer(self.VERTSUMI, self.tr('Sumidouros e vertedouros'), 
                                                            types=[QgsProcessing.TypeVectorPoint], 
                                                            defaultValue=None))
        self.addParameter(QgsProcessingParameterVectorLayer(self.DRENAGENS, self.tr('Drenagens'), 
                                                            types=[QgsProcessing.TypeVectorLine], 
                                                            defaultValue=None))
        #self.addParameter(QgsProcessingParameterVectorLayer('canais', 'Canais', 
        #                                                    types=[QgsProcessing.TypeVectorLine], 
        #                                                    defaultValue=None))
        self.addParameter(QgsProcessingParameterVectorLayer(self.MASSASDAGUA, self.tr('Massas de Agua'), 
                                                            types=[QgsProcessing.TypeVectorPolygon], 
                                                            defaultValue=None))
        
          # Camada de Saida.
        self.addParameter(QgsProcessingParameterFeatureSink(self.FLAGPOINT, self.tr('Erros pontuais'), 
                                                            type=QgsProcessing.TypeVectorPoint, 
                                                            createByDefault=True, 
                                                            supportsAppend=True, 
                                                            defaultValue='TEMPORARY_OUTPUT'))
        self.addParameter(QgsProcessingParameterFeatureSink(self.FLAGLINE, self.tr('Erros lineares'), 
                                                            type=QgsProcessing.TypeVectorLine, 
                                                            createByDefault=True, 
                                                            supportsAppend=True, 
                                                            defaultValue='TEMPORARY_OUTPUT'))
        self.addParameter(QgsProcessingParameterFeatureSink(self.FLAGPOLYGON, self.tr('Erros zonais'), 
                                                            type=QgsProcessing.TypeVectorPolygon, 
                                                            createByDefault=True, 
                                                            supportsAppend=True, 
                                                            defaultValue='TEMPORARY_OUTPUT'))
        
        
    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        pontos = self.parameterAsVectorLayer(parameters, self.VERTSUMI, context)
        drenagens = self.parameterAsVectorLayer(parameters, self.DRENAGENS, context)

        sinkFields = QgsFields()
        sinkFields.append(QgsField('ERRO', QVariant.String))
        (outputSink, outputDestId) = self.parameterAsSink(
                parameters,
                'FLAGPOINT',
                context,
                sinkFields,
                1,
                drenagens.sourceCrs()
            )
        
        def addFeatureError(sinkFields, geometry, errorText):
            errorFeat = QgsFeature(sinkFields)
            errorFeat.setGeometry(geometry)
            errorFeat.setAttribute('ERRO', errorText)
            return errorFeat
        
        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        #source = self.parameterAsSource(parameters, self.INPUT, context)
        #(sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
        #        context, source.fields(), source.wkbType(), source.sourceCrs())

        # Compute the number of steps to display within the progress bar and
        # get features from source
        #total = 100.0 / source.featureCount() if source.featureCount() else 0
        #features = source.getFeatures()

        attributesError = 0
        for ponto in pontos.getFeatures():
            pontoGeometry = ponto.geometry()
            noError = False
            for line in drenagens.getFeatures():
                lineGeometry = line.geometry()
                for part in lineGeometry.parts():
                    vertices = list(part)
                    for i in range(len(vertices)-1):
                        point = QgsGeometry.fromPointXY(QgsPointXY(vertices[i].x(), vertices[i].y()))
                        if pontoGeometry.intersects(point): noError = True
            if noError:
                outputSink.addFeature(addFeatureError(
                    sinkFields,
                    pontoGeometry,
                    'O sumidouro/vertedouro não está relacionado com uma drenagem.'))
                attributesError = attributesError + 1

        feedback.pushInfo(f"8. Há {attributesError} vertedouros/sumidouros isolados!")


        #for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
        #    if feedback.isCanceled():
        #        break

            # Add a feature in the sink
        #    sink.addFeature(feature, QgsFeatureSink.FastInsert)

            # Update the progress bar
        #    feedback.setProgress(int(current * total))

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        #return {self.OUTPUT: dest_id}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Solução do Projeto 2'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Projeto 2'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return Projeto2Solucao()
