# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ProgramacaoAplicadaGrupo4
                                 A QGIS plugin
 Solução do Grupo 4
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-05-04
        copyright            : (C) 2023 by Grupo 4
        emails               : e.tadeu.eb@ime.eb.br
                               raulmagno@ime.eb.br
                               arthur.cavalcante@ime.eb.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Grupo 4'
__date__ = '2023-05-04'
__copyright__ = '(C) 2023 by Grupo 4'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from code import interact
from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.Qt import QVariant, QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsProject,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingException,
                       QgsWkbTypes,
                       QgsExpressionContextUtils,
                       QgsPointXY,
                       QgsSpatialIndex,
                       QgsFeatureSink,
                       QgsFields,
                       QgsField,
                       QgsFeature,
                       QgsGeometry,
                       QgsExpression,
                       QgsVectorLayer,
                       QgsProcessingMultiStepFeedback,
                       QgsProcessingParameterVectorLayer,
                       QgsFields,
                       QgsFeature,
                       QgsField,
                       QgsGeometry,
                       QgsPointXY)
import processing


class Projeto3Solucao(QgsProcessingAlgorithm):
    """
    
    Este algoritmo realiza a generalização de edifícios próximos às rodovias.

    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    # Camadas de input
    INPUT = 'INPUT'
   
    # Camadas de output
    OUTPUT = 'OUTPUT'

    def initAlgorithm(self, config):

        self.addParameter(QgsProcessingParameterFeatureSource('edificios',
                self.tr('Insira a camada de pontos das edificações:'),
                [QgsProcessing.TypeVectorPoint]
            )
        )

        self.addParameter(QgsProcessingParameterFeatureSource('rodovias',
                self.tr('Insira a camada de linhas de rodovias:'),
                [QgsProcessing.TypeVectorLine]
            )
        )
                
        self.addParameter(QgsProcessingParameterNumber('distancia',
                self.tr('Insira a distância de deslocamento necessária'),
                defaultValue=30,
                type=QgsProcessingParameterNumber.Double
            )
        )

        
        self.addParameter(QgsProcessingParameterFeatureSink(
                'OUTPUT',
                self.tr('Camada de edificações generalizadas')
            )
        )
        
        
    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        edificios = self.parameterAsVectorLayer(
            parameters,
            'edificios',
            context
        )

        rodovias = self.parameterAsVectorLayer(
            parameters,
            'rodovias',
            context
        )

        distancia = self.parameterAsDouble(
            parameters,
            'distancia',
            context
        )

        
        sinkFields = edificios.fields()
        (output_sink, output_dest_id) = self.parameterAsSink(
                                            parameters,
                                            'OUTPUT',
                                            context,
                                            sinkFields,
                                            1,
                                            edificios.sourceCrs()
                                        )
        
        '''for feat in ed.getFeatures():
            output_sink.addFeature(feat)'''
        
        for ponto in edificios.getFeatures():
            geometriaPonto = ponto.geometry()
            for partes in geometriaPonto.parts():
                for p in partes.vertices():
                    x0 = p.x()
                    y0 = p.y()
                    xn = x0
                    yn = y0
                    for linha in rodovias.getFeatures():
                        geometriaLinha = linha.geometry()
                        for l in geometriaLinha.parts():
                            #feedback.pushInfo(str(l))
                            pontoaux = QgsGeometry.fromPointXY(QgsPointXY(xn,yn))
                            geomaux = QgsPoint(xn,yn)
                            distancia = pontoaux.distance(geometriaLinha)
                            if distancia < DIST:
                                pto_prox = QgsGeometryUtils.closestPoint(l,geomaux)
                                x_p = pto_prox.x()
                                y_p = pto_prox.y()
                                m = ((xn - x_p)**2 + (yn - y_p)**2)**0.5
                                xn = x_p + (DIST/m)*(xn - x_p)
                                yn = y_p + (DIST/m)*(yn - y_p)
                                
                                '''novo_pto = QgsGeometry.fromPointXY(QgsPointXY(xn,yn))
                                corr_feat = QgsFeature(sinkFields)
                                feedback.pushInfo(str(novo_pto))
                                #feedback.pushInfo("y:"+str(y0))
                                corr_feat.setGeometry(novo_pto)
                                #corr_feat.setAttribute('Corrigido','Ponto corrigido')
                                output_sink.addFeature(corr_feat)
                                remove_feat = QgsFeature(sinkFields)
                                remove_feat.QgsGeometryCollection.removeGeometry(QgsGeometry.fromPointXY(QgsPointXY(x0,y0)))'''
                    novo_pto = QgsGeometry.fromPointXY(QgsPointXY(xn,yn))
                    corr_feat = QgsFeature(sinkFields)
                    feedback.pushInfo(str(novo_pto))
                    corr_feat.setGeometry(novo_pto)
                    output_sink.addFeature(corr_feat)   
            '''
            for linha in rodovias.getFeatures():
                geometriaLinha = linha.geometry()
                
                distance = geometriaPonto.distance(geometriaLinha)
                #feedback.pushInfo("Ok:" + str(distance))
                if distance < distancia:
                    x0 = QgsPointXY(ponto['x'])
                    y0 = QgsPointXY(ponto['y'])
                    feedback.pushInfo("x:" + str(x0)+", y:" + str(y0))
                    #pto_prox = closestPoint()
            ''' 

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Solução do Projeto 3'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Projeto 3'

    # Definição da função auxiliar para definir as camadas de saída

    def prepareAndReturnFlagSink(self, parameters, source, wkbType, context, UI_FIELD):
        flagFields = self.getFlagFields()
        (flagSink, flag_id) = self.parameterAsSink(
            parameters,
            UI_FIELD,
            context,
            flagFields,
            wkbType,
            source.sourceCrs() if source is not None else QgsProject.instance().crs()
        )
        if flagSink is None:
            raise QgsProcessingException(self.invalidSinkError(parameters, UI_FIELD))
        return (flagSink, flag_id)
    
    #Função para auxiliar na não recorrência de código

    def getFlagFields(self):
        fields = QgsFields()
        fields.append(QgsField('Motivo',QVariant.String))
        return fields
    
    #Função para adicionar as Flags nos outputs.
    
    def flagFeature(self, flagGeom, flagText, sink=None):
        """
        Creates and adds to flagSink a new flag with the reason.
        :param flagGeom: (QgsGeometry) geometry of the flag;
        :param flagText: (string) Text of the flag
        """
        flagSink = self.flagSink if sink is None else sink
        newFeat = QgsFeature(self.getFlagFields())
        newFeat['Motivo'] = flagText
        newFeat.setGeometry(flagGeom)
        flagSink.addFeature(newFeat, QgsFeatureSink.FastInsert)

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return Projeto2Solucao()
