# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ProgramacaoAplicadaGrupo4
                                 A QGIS plugin
 Solução do Grupo 4
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-05-04
        copyright            : (C) 2023 by Grupo 4
        emails               : e.tadeu.eb@ime.eb.br
                               raulmagno@ime.eb.br
                               arthur.cavalcante@ime.eb.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Grupo 4'
__date__ = '2023-20-05'
__copyright__ = '(C) 2023 by Grupo 4'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.Qt import QVariant, QCoreApplication
from qgis.core import (QgsProcessing, 
                       QgsProcessingParameterMultipleLayers,
                       QgsProcessingAlgorithm,
                       QgsProcessingMultiStepFeedback,
                       QgsProcessingParameterVectorLayer,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterNumber)
import processing
import os

class Projeto4SolucaoComplementar(QgsProcessingAlgorithm):
    """
    Este algoritmo identifica os polígonos que têm quebra de continuidade nas bordas das molduras

    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.
    POLIGONOS = 'POLIGONOS'
    MOLDURAS = 'MOLDURAS'
    DISTANCIA = 'DISTANCIA'

    # Camadas de output
    OUTPUT = 'OUTPUT'

    def initAlgorithm(self, config):
        #INPUTS
        #self.addParameter(QgsProcessingParameterMultipleLayer(self.POLIGONOS, self.tr('Camadas de poligonos avaliadas'), 
        #                                                       layerType=QgsProcessing.TypeVectorPolygon, 
        #                                                       defaultValue=None))
        
        self.addParameter(QgsProcessingParameterVectorLayer(self.POLIGONOS, self.tr('Camadas de poligonos avaliadas'), 
                                                            types=[QgsProcessing.TypeVectorPolygon], 
                                                            defaultValue=None))

        self.addParameter(QgsProcessingParameterVectorLayer(self.MOLDURAS, self.tr('Insira as molduras'), 
                                                            types=[QgsProcessing.TypeVectorPolygon], 
                                                            defaultValue=None))
                
        self.addParameter(QgsProcessingParameterFeatureSink(self.OUTPUT, self.tr('Polígonos com erro de Borda'),
                                                            type=QgsProcessing.TypeVectorAnyGeometry,
                                                            createByDefault=True,
                                                            supportsAppend=True,
                                                            defaultValue='TEMPORARY_OUTPUT'))

    def processAlgorithm(self, parameters, context, model_feedback):
        # Use a multi-step feedback, so that individual child algorithm progress reports are adjusted for the
        # overall progress through the model
        feedback = QgsProcessingMultiStepFeedback(12, model_feedback)
        results = {}
        outputs = {}
        
        poligonos = self.parameterAsVectorLayer(
            parameters, 
            self.POLIGONOS, 
            context
        )
        molduras = self.parameterAsVectorLayer(
            parameters, 
            self.MOLDURAS, 
            context
        )

        # Indices Espaciais Poligonos
        alg_params = {
            'INPUT': poligonos
        }
        outputs['IndicesEspaciaisPoligonos'] = processing.run('native:createspatialindex', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(1)
        if feedback.isCanceled():
            return {}
        
        # Dissolver molduras de poligonos (para gerar limite externo)
        lim_ext_pol = processing.run("native:dissolve", 
                        {'INPUT':molduras,
                       'FIELD':[],
                       'SEPARATE_DISJOINT':False,
                       'OUTPUT':'TEMPORARY_OUTPUT'})

        feedback.setCurrentStep(2)
        if feedback.isCanceled():
            return {}
        
        # Converter molduras de poligonos para linhas

        molduras_lin = processing.run("native:polygonstolines", 
                                      {'INPUT':molduras
                                       ,'OUTPUT':'TEMPORARY_OUTPUT'})

        feedback.setCurrentStep(3)
        if feedback.isCanceled():
            return {}
        
        # Converter limite externo para linhas
        lim_ext_lin = processing.run("native:polygonstolines", 
                                      {'INPUT':lim_ext_pol
                                       ,'OUTPUT':'TEMPORARY_OUTPUT'})

        feedback.setCurrentStep(4)
        if feedback.isCanceled():
            return {}

        # Delimitacao das fronteiras internas

        lim_int_molduras = processing.run("native:symmetricaldifference", {'INPUT':molduras_lin,
                                                                           'OVERLAY':lim_ext_lin,
                                                                           'OVERLAY_FIELDS_PREFIX':'',
                                                                           'OUTPUT':'TEMPORARY_OUTPUT',
                                                                           'GRID_SIZE':None})

        feedback.setCurrentStep(5)
        if feedback.isCanceled():
            return {}

        # Selecionando os poligonos que serao avaliados

        pol_analise = processing.run("native:extractbylocation", {'INPUT':pol_analise,
                                                                  'PREDICATE':[0], #Intersecta
                                                                  'INTERSECT':lim_int_molduras,
                                                                  'OUTPUT':'TEMPORARY_OUTPUT'})
 

        feedback.setCurrentStep(6)
        if feedback.isCanceled():
            return {}
        
        # Delimitando poligonos validos

        pol_validos = processing.run("native:extractbylocation", {'INPUT':pol_analise,
                                                                  'PREDICATE':[7], #Cruza
                                                                  'INTERSECT':lim_int_molduras,
                                                                  'OUTPUT':'TEMPORARY_OUTPUT'})
    
        feedback.setCurrentStep(7)
        if feedback.isCanceled():
            return {}

        # Encontrando poligonos errados

        pol_erro = lim_int_molduras = processing.run("native:symmetricaldifference", {'INPUT':pol_analise,
                                                                           'OVERLAY':pol_validos,
                                                                           'OVERLAY_FIELDS_PREFIX':'',
                                                                           'OUTPUT':'TEMPORARY_OUTPUT',
                                                                           'GRID_SIZE':None})

        feedback.setCurrentStep(8)
        if feedback.isCanceled():
            return {}
        
        # Delimitando erros em linha

        erro_linha = processing.run("native:clip", {'INPUT':lim_int_molduras,
                                       'OVERLAY':pol_erro,
                                       'OUTPUT':'TEMPORARY_OUTPUT'})

        feedback.setCurrentStep(9)
        if feedback.isCanceled():
            return {}
        
        #Criando coluna de id
        
        feedback.setCurrentStep(10)
        if feedback.isCanceled():
            return {}
        
        # Descartar campos excedentes
        alg_params = {
            'COLUMN': ['Azimute','n','distance','feature_x','feature_y','nearest_x','nearest_y'],
            'INPUT': outputs['AlimentandoAColunaRotacao']['OUTPUT'],
            'OUTPUT': parameters[self.OUTPUT]
        }
        outputs['DescartarCamposExcedentes'] = processing.run('native:deletecolumn', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        # Definindo resultado
        results[self.OUTPUT] = outputs[erro_linha]['OUTPUT']

        feedback.setCurrentStep(11)
        if feedback.isCanceled():
            return {}

        # Configurando o estilo de camada de saida

           # Get the path to the plugin directory
        plugin_dir = os.path.dirname(__file__)
        style_file = os.path.join(plugin_dir, 'edificacoes.qml')

        alg_params = {
            'INPUT': outputs['DescartarCamposExcedentes']['OUTPUT'],
            'STYLE': style_file
        }
        outputs['ConfigurandoOEstiloDeCamadaDeSaida'] = processing.run('native:setlayerstyle', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        return results

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Solução Complementar do Projeto 4'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Projeto 4'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return Projeto4SolucaoComplementar()
    
  