# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ProgramacaoAplicadaGrupo4
                                 A QGIS plugin
 Solução do Grupo 4
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-05-04
        copyright            : (C) 2023 by Grupo 4
        emails               : e.tadeu.eb@ime.eb.br
                               raulmagno@ime.eb.br
                               arthur.cavalcante@ime.eb.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Grupo 4'
__date__ = '2023-20-05'
__copyright__ = '(C) 2023 by Grupo 4'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.Qt import QVariant, QCoreApplication
from qgis.core import (QgsProcessing, 
                       QgsProcessingParameterMultipleLayers,
                       QgsProcessingAlgorithm,
                       QgsProcessingMultiStepFeedback,
                       QgsProcessingParameterVectorLayer,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterNumber)
import processing
import os

class Projeto4SolucaoComplementar(QgsProcessingAlgorithm):
    """
    Este algoritmo identifica os polígonos que têm quebra de continuidade nas bordas das molduras

    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.
    POLIGONOS = 'POLIGONOS'
    MOLDURAS = 'MOLDURAS'
    DISTANCIA = 'DISTANCIA'

    # Camadas de output
    OUTPUT = 'OUTPUT'

    def initAlgorithm(self, config):
        #INPUTS
        #self.addParameter(QgsProcessingParameterMultipleLayer(self.POLIGONOS, self.tr('Camadas de poligonos avaliadas'), 
        #                                                       layerType=QgsProcessing.TypeVectorPolygon, 
        #                                                       defaultValue=None))
        
        self.addParameter(QgsProcessingParameterVectorLayer(self.POLIGONOS, self.tr('Camada de poligonos avaliados'), 
                                                            types=[QgsProcessing.TypeVectorPolygon], 
                                                            defaultValue=None))

        self.addParameter(QgsProcessingParameterVectorLayer(self.MOLDURAS, self.tr('Insira as molduras'), 
                                                            types=[QgsProcessing.TypeVectorPolygon], 
                                                            defaultValue=None))
                
        self.addParameter(QgsProcessingParameterFeatureSink(self.OUTPUT, self.tr('Polígonos com erro de Borda'),
                                                            type=QgsProcessing.TypeVectorAnyGeometry,
                                                            createByDefault=True,
                                                            supportsAppend=True,
                                                            defaultValue='TEMPORARY_OUTPUT'))

    def processAlgorithm(self, parameters, context, model_feedback):
        # Use a multi-step feedback, so that individual child algorithm progress reports are adjusted for the
        # overall progress through the model
        feedback = QgsProcessingMultiStepFeedback(9, model_feedback)
        results = {}
        outputs = {}
        
        poligonos = self.parameterAsVectorLayer(
            parameters, 
            self.POLIGONOS, 
            context
        )
        molduras = self.parameterAsVectorLayer(
            parameters, 
            self.MOLDURAS, 
            context
        )

        # Corrigir geometrias
        alg_params = {
            'INPUT': poligonos,
            'METHOD': 1,  # Estrutura
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['CorrigirGeometrias'] = processing.run('native:fixgeometries', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(1)
        if feedback.isCanceled():
            return {}

        # Dissolver molduras
        alg_params = {
            'FIELD': [''],
            'INPUT': molduras,
            'SEPARATE_DISJOINT': False,
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['DissolverMolduras'] = processing.run('native:dissolve', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(2)
        if feedback.isCanceled():
            return {}

        # Indices espaciais Poligonos
        alg_params = {
            'INPUT': outputs['CorrigirGeometrias']['OUTPUT']
        }
        outputs['IndicesEspaciaisPoligonos'] = processing.run('native:createspatialindex', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(3)
        if feedback.isCanceled():
            return {}

        # Limite externo das molduras
        alg_params = {
            'INPUT': outputs['DissolverMolduras']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['LimiteExternoDasMolduras'] = processing.run('native:polygonstolines', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(4)
        if feedback.isCanceled():
            return {}

        # Molduras em linha
        alg_params = {
            'INPUT': molduras,
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['MoldurasEmLinha'] = processing.run('native:polygonstolines', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(5)
        if feedback.isCanceled():
            return {}

        # Fronteiras entre molduras
        alg_params = {
            'GRID_SIZE': None,
            'INPUT': outputs['MoldurasEmLinha']['OUTPUT'],
            'OVERLAY': outputs['LimiteExternoDasMolduras']['OUTPUT'],
            'OVERLAY_FIELDS_PREFIX': '',
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['FronteirasEntreMolduras'] = processing.run('native:symmetricaldifference', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(6)
        if feedback.isCanceled():
            return {}

        # Buffer infinitesimal
        alg_params = {
            'DISSOLVE': False,
            'DISTANCE': 0.001,
            'END_CAP_STYLE': 1,  # Plano
            'INPUT': outputs['FronteirasEntreMolduras']['OUTPUT'],
            'JOIN_STYLE': 1,  # Pontiagudo
            'MITER_LIMIT': 2,
            'SEGMENTS': 5,
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['BufferInfinitesimal'] = processing.run('native:buffer', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(7)
        if feedback.isCanceled():
            return {}

        # Selecionando poligonos na regiao de borda
        alg_params = {
            'INPUT': outputs['IndicesEspaciaisPoligonos']['OUTPUT'],
            'INTERSECT': outputs['BufferInfinitesimal']['OUTPUT'],
            'PREDICATE': [0],  # interseccionam
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['SelecionandoPoligonosNaRegiaoDeBorda'] = processing.run('native:extractbylocation', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(8)
        if feedback.isCanceled():
            return {}

        # Interseção 
        alg_params = {
            'GRID_SIZE': None,
            'INPUT': outputs['FronteirasEntreMolduras']['OUTPUT'],
            'INPUT_FIELDS': [''],
            'OVERLAY': outputs['SelecionandoPoligonosNaRegiaoDeBorda']['OUTPUT'],
            'OVERLAY_FIELDS': [''],
            'OVERLAY_FIELDS_PREFIX': '',
            'OUTPUT': parameters[self.OUTPUT]
        }
        outputs['Interseo'] = processing.run('native:intersection', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        results[self.OUTPUT] = outputs['Interseo']['OUTPUT']
        return results

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Solução Complementar do Projeto 4'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Projeto 4'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return Projeto4SolucaoComplementar()
    
  